# Run this command to start the database:
# docker-compose up --build
version: "3"
services:
  experiment:
    image: danielpsjr/deepal:latest
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        - USER_ID=${USER_ID}
        - GROUP_ID=${GROUP_ID}
    volumes:
      - ${PWD}:/app
    ports:
      - "8888:8888"
      - "8049:8049"
    depends_on:
      - db
    links:
      - db:db
#    entrypoint: [ "/bin/sh","-c" ]
    command: tail -f /dev/null
#    - |
#      python db/connection.py
#      tail -f /dev/null

  db:
    hostname: 127.0.0.1
    image: ankane/pgvector
    ports:
      - "5432:5432"
    restart: always
    environment:
      - POSTGRES_DB=al_provenance
      - POSTGRES_USER=provenance
      - POSTGRES_PASSWORD=Provenance
    volumes:
      - ./db/init.sql:/docker-entrypoint-initdb.d/init.sql